# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-vpc-peering
  description: This component is responsible for creating a peering connection between two VPCs existing in different AWS accounts
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





